### ISSUE TITLE
Error when setting number of threads

### ISSUE THREAD

**Issue by jromanowska** [senresearch/LiteQTL.jl#18]
This line gives an error:

https://github.com/senresearch/LiteQTL.jl/blob/87a5740c67a43d9d65abea92cf136d28229f7787/src/util.jl#L16

I found that using `BLAS.get_num_threads()` instead of the line mentioned, works fine.

**Comment by sens** [comment]
You are probably right. In the successor package BulkLMM we are using the `get_num_threads` function as you are suggesting.

**Comment by jromanowska** [comment]
Oh, "successor package"? I will check that one out! I'm looking for a fast (and memory-efficient) way to calculate methylation-QTLs

**Comment by sens** [comment]
Yes, please take a look at [https://github.com/senresearch/BulkLMM.jl](https://github.com/senresearch/BulkLMM.jl). The main difference from LiteQTL is that it is designed to perform LMM (linear mixed model) scans as opposed to linear model (LM) scans that LiteQTL is designed to do. BulkLMM uses CPU multi-threading, if available, but does not have a GPU option that is available in LiteQTL.  You may also be interested in BigRiverQTLPlots which can plot QTL and eQTL (and methylation) scans.

**Comment by jromanowska** [comment]
Wow, thank you for that - I will investigate!

**Comment by GregFa** [comment]
I fixed the bug that @jromanowska suggested and I also updated the compatibility of packages. 
Thank you, @jromanowska, for pointing out this issue.
