### ISSUE TITLE
Error in `scan` when calculating p-values

### ISSUE THREAD

**Issue by jromanowska** [senresearch/LiteQTL.jl#20]
https://github.com/senresearch/LiteQTL.jl/blob/c6360c70843a74fb70c396a7551543817a4b8ca0/src/cpu.jl#L208

I get error when running the `scan` function and requesting `pval` as output:

```
> @time pval_matrix_no_cov = scan(
    Y,
    G,
    export_matrix = export_matrix,
    maf_threshold = 0.00,
    usegpu = false,
    lod_or_pval = "pval"
);

ERROR: UndefVarError: `pval_calc` not defined
```
(I was just running the example in https://github.com/senresearch/LiteQTL.jl/blob/master/example/spleen_analysis.jl and then modifying to get various outputs.)

**Comment by GregFa** [comment]
I have addressed the error and updated the package to version v0.2.4. @jromanowska Could you please update to this latest version and confirm whether the issue has been resolved on your end? Your feedback would be greatly appreciated.

**Comment by jromanowska** [comment]
Fantastic! It's working great now!
